feat: search API on admin page
Repick-official/repick-server-v2 pull request #129
Opened 2024-08-04 18:50 UTC by sky980221

관리자페이지 검색 API
---
두 가지 검색 기능을 구현합니다.

상품 종합 현황에서 상품 코드로만 검색
---
기존 상품 종합 현황보기 기능에서 userId를 추가로 받아 검색이 가능하도록 하였습니다.
getClothingSalesProductCount만 약간 수정하여 중복되는 코드 최대한 줄였습니다. 
userId가 null이면 기존처럼 전체 현황이 출력됩니다. 

![image](https://github.com/user-attachments/assets/28fbb6a4-b8c7-4382-a9c5-0bd2077b64d9)

옷장 정리 현황에서 기간으로 검색
---
검색 시작 날짜와 검색 종료 날짜를 입력하면 그 사이에 신청일이 있는 clothingSales들을 출력해줍니다. 

나중에 날짜로 검색하는 기능들이 더 생길 것 같아 DateRangePageCondition라는 page를 만들어서 입력을 받았는데, 기존에 있던 PageCondition에 startDate, endDate만 추가적으로 입력 받는게 더 좋을 것 같다면 그렇게 바꾸겠습니다.

1일, 1개월 같은 검색 기간 설정은 프론트 단에서 계산해주는 것으로 알고 생략하였습니다.

현재는 검색 시작 날짜와 종료 날짜 둘 중 하나라도 비어있으면 전체를 출력하도록 만들었는데, 이 부분 수정이 필요하면 바꾸겠습니다. (피그마 보니까 직접 입력이라는 옵션이 존재하더라구요)

![image](https://github.com/user-attachments/assets/55220637-fabe-4088-9675-d9c7f2964ce1)

2024-08-05 06:29 UTC, mushroom1324 requested changes
수고하셨습니다! 코멘트 확인 바랍니다!

2024-08-05 06:29 UTC, mushroom1324 commented on src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
> +        }
코드에 로직 에러가 있습니다
지금 코드에서 먼저 PageSize에 맞게 가져온 다음 날짜로 filter를 거칩니다
먼저 필터링을 거친 후 Size에 맞게 가져와야 합니다!

2024-08-05 06:29 UTC, mushroom1324 commented on src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
> +                        clothingSales.createdDate
한 product는 현재 product.clothing_sales_id에 대해 unique 합니다. 수정이 필요해보여요!

2024-08-05 06:29 UTC, mushroom1324 commented on src/main/java/com/example/repick/global/page/DateRangePageCondition.java
> +public record DateRangePageCondition (
DateRangePageCondition보다는 기존 PageCondition 사용 + DateCondition을 추가로 만드는건 어떨까요?

2024-08-05 06:32 UTC, sky980221 commented on src/main/java/com/example/repick/global/page/DateRangePageCondition.java
> +public record DateRangePageCondition (
넹 위에 말씀 드린대로 그걸 고민하고 있었습니다! 그렇게 수정할게여 😀

2024-08-05 13:25 UTC, sky980221 commented on src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
> +                        clothingSales.createdDate
감사합니다 감사합니다 ☺️

2024-08-05 17:15 UTC, sky980221 commented on src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
> +        }
감사합니다 수정했습니다 !

2024-08-06 01:19 UTC, hyunihs approved these changes
수고하셨습니다 ☺️

2024-08-06 01:19 UTC, hyunihs commented on src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
> +        Page<GetClothingSalesProductCount> pages = productRepository.getClothingSalesProductCount(pageCondition.toPageable(), null);
controller에서 userId null 구분해서 나눈 두 메소드가 사실상 같은 구조여서 구분 안하고 둘이 합쳐도 될 것 같아요!

2024-08-06 14:11 UTC, mushroom1324 approved these changes
LGTM 😉

2024-08-06 16:52 UTC, sky980221 commented on src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
> +        Page<GetClothingSalesProductCount> pages = productRepository.getClothingSalesProductCount(pageCondition.toPageable(), null);
감사합니다 !!!! 수정했습니다 !!!!!

2024-08-06 16:53 UTC, merged