네이버 소셜로그인 기능
Repick-official/repick-server-v2 pull request #54
Opened 2024-05-05 16:09 UTC by sky980221

![image](https://github.com/Repick-official/repick-server-v2/assets/76761816/762b82d6-f926-4395-afcf-acf413c603f2)
네이버 엑세스 토큰으로 내부 토큰을 발급하는 기능을 구현합니다.

2024-05-06 04:14 UTC, mushroom1324 requested changes
수고하셨습니다! 노션에 환경변수 업데이트 바랍니다!!

2024-05-06 04:14 UTC, mushroom1324 commented on src/main/java/com/example/repick/global/jwt/UserDetailsImpl.java
> +import com.example.repick.global.error.exception.CustomException;
Unused import statement 삭제해주세염

2024-05-06 04:14 UTC, mushroom1324 commented on src/main/java/com/example/repick/global/error/exception/CustomException.java
> +    public CustomException(String s) {
이거 어디에 쓰이나요? 제 생각엔 기존에 있는 메서드 써도 될 것 같아용

2024-05-06 04:14 UTC, mushroom1324 commented on src/main/java/com/example/repick/global/error/exception/CustomException.java
> +    public CustomException(String s) {
이것두 안쓰이는거면 삭제하는게 좋을 것 같습니다!

2024-05-06 15:40 UTC, sky980221 commented on src/main/java/com/example/repick/global/jwt/UserDetailsImpl.java
> +import com.example.repick.global.error.exception.CustomException;
넵 수정 완료했습니다

2024-05-06 15:40 UTC, sky980221 commented on src/main/java/com/example/repick/global/error/exception/CustomException.java
> +    public CustomException(String s) {
넹 수정 완료햇습니다

2024-05-07 09:24 UTC, chanhyeokseo approved these changes
LGTM 수고하셨습니다!

2024-05-08 05:19 UTC, merged