내 사이즈 상품 보기 기능 구현
Repick-official/repick-server-v2 pull request #89
Opened 2024-06-09 15:39 UTC by sky980221

![image](https://github.com/Repick-official/repick-server-v2/assets/76761816/0d28a262-2172-4139-a3bb-a9ab426c1f6c)
 - 내 사이즈로 찾기 여부를 ProductFilter DTO에 isMySize라는 변수를 추가하여 구현

```
**간단한 수도 코드**
if isMySize == True: 
   if parent field == 상의, 아우터, 원피스
      sizes = User Entity’s topSize
   elif parent field == 하의, 스커트:
      sizes = User Entity’s bottomSize
```
- getUserSizesForCategory라는 메소드를 생성하여 카테고리에 따라 상/하의 중 어떤 사이즈를 가지고 올지 결정

2024-06-10 07:28 UTC, mushroom1324 requested changes
수고하셨습니다! 리뷰 확인 부탁드려요~

2024-06-10 07:28 UTC, mushroom1324 commented on src/main/java/com/example/repick/domain/product/service/ProductService.java
> +        );
```suggestion
            productFilter = new ProductFilter(
                    productFilter.keyword(),
                    productFilter.gender(),
                    productFilter.category(),
                    productFilter.styles(),
                    productFilter.minPrice(),
                    productFilter.maxPrice(),
                    productFilter.brandNames(),
                    productFilter.qualityRates(),
                    sizes,
                    productFilter.isMySize()
            );
        }
```

이렇게 바꾸면 MySize로 보는 사람의 경우에만 새로운 ProductFilter를 만들기 때문에 더 괜찮지 않을까요?

2024-06-11 16:15 UTC, sky980221 commented on src/main/java/com/example/repick/domain/product/service/ProductService.java
> +        );
감사합니다 ~ 수정했습니다 ㅎㅎ

2024-06-11 16:25 UTC, mushroom1324 approved these changes
LGTM 👏

2024-06-11 16:29 UTC, merged